name: yolofusion
description: A professional document generation app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  animate_do: ^3.3.1
  image_picker: ^1.1.0
  camera: ^0.11.2
  web_socket_channel: ^3.0.1
  http: ^1.2.2
  image: ^4.2.0
  video_player: ^2.9.1
  video_player_win: ^2.0.0
  file_selector: ^1.0.3
  file_selector_windows: ^0.9.3+4
  file_selector_macos: ^0.9.0+3
  file_selector_linux: ^0.9.2+4
  permission_handler: ^12.0.1
  camera_windows: ^0.2.6+2

  device_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/google_icon.png
    - assets/apple.png
    - assets/image_0.jpg
    - assets/image_1.jpg
    - assets/image_2.jpg
    - assets/image_3.jpg
    - assets/image_4.jpg
    - assets/yolo_architecture.png
    - assets/image_face.jpg
    - assets/image_object.jpg
    - assets/image_activity.jpg
    - assets/image_plant1.jpg
